---
openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  "/tasks/":
    get:
      summary: Read Tasks
      operationId: read_tasks_tasks__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Read Tasks Tasks  Get
                type: array
                items:
                  "$ref": "#/components/schemas/Task"
    post:
      summary: Create Task
      operationId: create_task_tasks__post
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TaskCreate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
  "/tasks/{task_id}":
    get:
      summary: Read Task
      operationId: read_task_tasks__task_id__get
      parameters:
      - required: true
        schema:
          title: Task Id
          type: integer
        name: task_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    put:
      summary: Update Task
      operationId: update_task_tasks__task_id__put
      parameters:
      - required: true
        schema:
          title: Task Id
          type: integer
        name: task_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/TaskUpdate"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
    delete:
      summary: Delete Task
      operationId: delete_task_tasks__task_id__delete
      parameters:
      - required: true
        schema:
          title: Task Id
          type: integer
        name: task_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Task"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            "$ref": "#/components/schemas/ValidationError"
    Task:
      title: Task
      required:
      - title
      - description
      - status
      - id
      - created_at
      type: object
      properties:
        title:
          title: Title
          type: string
        description:
          title: Description
          type: string
        status:
          title: Status
          type: string
        id:
          title: Id
          type: integer
        created_at:
          title: Created At
          type: string
          format: date-time
    TaskCreate:
      title: TaskCreate
      required:
      - title
      - description
      - status
      type: object
      properties:
        title:
          title: Title
          type: string
        description:
          title: Description
          type: string
        status:
          title: Status
          type: string
    TaskUpdate:
      title: TaskUpdate
      required:
      - title
      - description
      - status
      type: object
      properties:
        title:
          title: Title
          type: string
        description:
          title: Description
          type: string
        status:
          title: Status
          type: string
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
            - type: string
            - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
